name: Kubernetes

on:
  workflow_call:

jobs: 

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurando credenciais da aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-2

    - run: git clone https://github.com/FlavioAmancio/infra_ci_kubernetes.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - run: terraform -chdir=infra_ci_kubernetes/env/Homolog init

    - run: terraform -chdir=infra_ci_kubernetes/env/Homolog apply -auto-approve

    - run: echo "$(terraform -chdir=infra_ci_kubernetes/env/Homolog output -raws IP_db)"
      id: URL
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4

    - run: aws sts get-caller-identity

    - run: aws eks update-kubeconfig --region us-east-2 --name homolog2

    - run: kubectl get svc    

    - run: kubectl create secret generic dbhost --from-literal=HOST= ${{ steps.URL.output.stdout }}
    - run: kubectl create secret generic dbport --from-literal=DBPORT= ${{ secrets.DBPORT }}
    - run: kubectl create secret generic dbuser --from-literal=USER= ${{ secrets.DBUSER }}
    - run: kubectl create secret generic dbpassword --from-literal=PASSWORD= ${{ secrets.DBPASSWORD }}
    - run: kubectl create secret generic dbname --from-literal=DBNAME= ${{ secrets.DBNAME }}
    - run: kubectl create secret generic port --from-literal=PORT=8000
