name: Kubernetes

on:
  workflow_call:

jobs: 

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurando credenciais da aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ID_CHAVE_ACESSO }}
        aws-secret-access-key: ${{ secrets.CHAVE_SECRETA }}
        aws-region: us-east-2

    - run: git clone https://github.com/FlavioAmancio/infra_ci_kubernetes.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - run: terraform -chdir=infra_ci_kubernetes/env/Homolog init

    - run: terraform -chdir=infra_ci_kubernetes/env/Homolog destroy -auto-approve
    - run: return 1

    - run: terraform -chdir=infra_ci_kubernetes/env/Homolog apply -auto-approve

    - run: echo "$(terraform -chdir=infra_ci_kubernetes/env/Homolog output -raws IP_db)"
      id: URL
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4

    - run: aws sts get-caller-identity

    - run: aws eks update-kubeconfig --region us-east-2 --name homolog2

    - run: kubectl get svc    
    
    - run: kubectl delete secret dbhost --ignore-not-found
    - run: kubectl create secret generic dbhost --from-literal=HOST= ${{ steps.URL.outputs.stdout }}
   
    - run: kubectl delete secret dbport --ignore-not-found
    - run: kubectl create secret generic dbport --from-literal=DBPORT= ${{ secrets.DBPORT }}

    - run: kubectl delete secret dbuser --ignore-not-found
    - run: kubectl create secret generic dbuser --from-literal=USER= ${{ secrets.DBUSER }}
    
    - run: kubectl delete secret dbpassword --ignore-not-found
    - run: kubectl create secret generic dbpassword --from-literal=PASSWORD= ${{ secrets.DBPASSWORD }}
    
    - run: kubectl delete secret dbname --ignore-not-found
    - run: kubectl create secret generic dbname --from-literal=DBNAME= ${{ secrets.DBNAME }}
    
    - run: kubectl delete secret port --ignore-not-found
    - run: kubectl create secret generic port --from-literal=PORT=8000

    - run: kubectl apply -f infra_ci_kubernetes/go.yaml

    - run: kubectl set image deployment/go-api go=amancioflaviodevops/go_ci:${{github.run_number}}
